version: '3'
services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8000}:8000'
    restart: always
    volumes:
      - '/var/www/html'
    
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: unless-stopped
    

  redis:
    image: redis:latest
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s



volumes:
  mysql:
    driver: local
  redis:
    driver: local