FROM redis:latest

# Copy custom Redis configuration file if required
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the default Redis port
EXPOSE 6379

# Start Redis service
CMD ["redis-server"]